# Generated by Django 2.2 on 2021-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0003_auto_20210414_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='dias',
        ),
        migrations.AddField(
            model_name='permiso',
            name='observacion',
            field=models.CharField(default='pendiente validacion', max_length=200),
        ),
    ]
