# Generated by Django 2.2 on 2021-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0004_auto_20210414_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='observacion',
            field=models.CharField(default='observacion', max_length=200),
        ),
    ]
