# Generated by Django 2.2 on 2021-04-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0005_auto_20210414_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='remunerado',
        ),
    ]
