# Generated by Django 2.2 on 2021-04-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0006_remove_permiso_remunerado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='observacion',
        ),
    ]
