# Generated by Django 2.2 on 2021-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0008_permiso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(default='tipo de incapacidad', max_length=200),
        ),
    ]
